<?php $__env->startSection('banner'); ?>
<div class="col-lg-12" align="center" style="background-color:#ffcf29">
   <img src="<?php echo e(url('/')); ?>/new_heading.png" class="img-responsive">
</div>
<?php $__env->stopSection(); ?>
<?php $__env->startSection('sidebar'); ?>
<?php echo $__env->make('partial.header', array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>
<?php echo $__env->make('partial.aside', array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>
<?php $__env->stopSection(); ?>
<?php $__env->startSection('body'); ?>
<style type="text/css">
  .sticky{
    background: #eaffe4;
    margin: 10px;
    box-shadow: 0px 3px 3px 0px rgba(0, 0, 0, 0.23);
    padding: 5px;
  }
  .bootstrap-select>.dropdown-toggle.bs-placeholder, .bootstrap-select>.dropdown-toggle.bs-placeholder:active, .bootstrap-select>.dropdown-toggle.bs-placeholder:focus, .bootstrap-select>.dropdown-toggle.bs-placeholder:hover {
    color: #000;
    background: #27c24c;
}
</style>
<div class="bg-light lter b-b wrapper-md">
   <h1 class="m-n font-thin h3">View Benefits</h1>
</div>


<?php if(isset($selected)): ?>
<div class="bg-light lter b-b wrapper-md">
<h2 class="m-n font-thin h3">SELECT TCN</h2>
<form action="" method="post">
<?php echo e(csrf_field()); ?>


<button  name="tcn" value="<?php echo e($selected->id); ?>" class="btn btn-success"><?php echo e($selected->tcnType); ?></button>

  <a href="<?php echo e(URL::to('/')); ?>/admin/benefit/view" class="btn btn-dark">BACK</a>
</form>
</div>
<?php else: ?>
<div class="bg-light lter b-b wrapper-md">
<h2 class="m-n font-thin h3">SELECT TCN</h2>
<form action="" method="post">
<?php echo e(csrf_field()); ?>

<?php $__currentLoopData = $tcns; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $tcn): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
<button  name="tcn" value="<?php echo e($tcn->id); ?>" class="btn btn-success"><?php echo e($tcn->tcnType); ?></button>
<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
  <a href="<?php echo e(URL::to('/')); ?>/admin/benefit/view" class="btn btn-dark">BACK</a>
</form>
</div>
<?php endif; ?>




<?php if(isset($selected)): ?>
<div class="bg-light lter b-b wrapper-md">
<form action="post">
<select class="selectpicker" data-live-search="true" onchange="fetchtcn()">
<?php $__currentLoopData = $bd; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $benefit): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
  <?php  $date = Carbon::create($benefit->year, $benefit->month, 5, 0, 0, 0);   ?>
  <option data-tokens="<?php echo e($date->format('m')); ?>/<?php echo e($date->format('Y')); ?> <?php echo e($date->format('Y')); ?> <?php echo e($date->format('F')); ?>"><?php echo e($date->format('F')); ?> - <?php echo e($date->year); ?> </option>
<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
</select> 
</form>
</div>
<?php endif; ?>



<div class="col-lg-6 col-md-6 col-sm-12" style="margin-top: 20px;">
      <div class="panel b-a">
        
        <ul class="list-group">
          <li class="list-group-item">
            <span style="font-size: 20px" >TCN A </span>(Generated on 01/12/2017)
          </li>
          <li class="list-group-item">
            <i class="icon-check text-success m-r-xs"></i> BENEFIT GENERATED FOR <strong>JULY 2010</strong>
          </li>
          <li class="list-group-item">
            <i class="icon-check text-success m-r-xs"></i> TOTAL NUMBER OF TCN : 16
          </li>
          <li class="list-group-item">
            <i class="icon-check text-success m-r-xs"></i> GENERATED BY MS. MOLLY THOMAS
          </li>
          <li class="list-group-item">
            <i class="icon-cloud-download text-success m-r-xs"></i> <a><span style="color:green" >DOWNLOAD</span> BANK REPORT</a>
          </li>
          <li class="list-group-item">
            <i class="icon-cloud-download text-success m-r-xs"></i> <a><span style="color:green" >DOWNLOAD</span> BENEFIT REPORT</a>
          </li>
        </ul>
      </div>
    </div>







<div class="col-md-12"><br></div>



<?php $__env->stopSection(); ?>
<?php $__env->startSection('jquery'); ?>https://www.google.co.in/url?sa=t&rct=j&q=&esrc=s&source=web&cd=7&ved=0ahUKEwjL79G3r9HVAhUJK48KHYpmDFYQFghhMAY&url=https%3A%2F%2Fpaytm.com%2Fbus-tickets&usg=AFQjCNE8G6BWrNXGYOxHlq9kbRsyBm7-uA
<script type="text/javascript">
        var value = $('#scheme').val();
        if(value == '') {
            $('#declare').attr('disabled',true);
        }


</script>

</script>
<?php $__env->stopSection(); ?>
<?php echo $__env->make('layout.erp', array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>